# -*- coding: utf-8 -*-
"""add1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10EM4t16vEhsWTAD4wT-_oNUKBZCasXP7
"""

A = 7
B = 1
C = A + B
print(C)

